### PR TITLE
Speed up subtree count by avoiding recounting of trees

### PR DESCRIPTION
**Pull request by andersjohansson**
This speeds up org-wc-display significantly.

We assume that a heading line with an :org-wc text property was
correctly counted, since all text-properties are generally cleared at the
start of recountings in org-wc-count-subtrees

----

This feature is added atop the changes I’ve made in #25 and #28 (I think this makes most sense), and this branch contains an ugly merge-commit. If you decide to pull it all perhaps this branch should be rebased first.

# Benchmarks
Running
`(benchmark-run (org-wc-count-subtrees) 50)`

With new algorithm:
`(0.989303116 1 0.09430427399999886)`

With old:
`(3.44278043 2 0.18866386999999918)`

### CODE REVIEW

**Comment by andersjohansson** [comment]
About the benchmarks: Tested on a draft of a paper with ~8000 words in counted trees and lots of commented/noexport-trees. The counts for every subtree when running `org-wc-display` were exactly the same.

**Comment by tesujimath** [comment]
Really appreciate your work on all these pull requests. Will try to work through them all at the weekend and get everything merged. Thank you!

**Comment by tesujimath** [comment]
This is great!  Thanks @andersjohansson 

Can you please fix the conflict, then I'll get this merged right away?

**Comment by andersjohansson** [comment]
A rebase to current master made it clean.

**Comment by tesujimath** [comment]
Thanks!

**Pull request merged**
