### PR TITLE
Customize exclusion of tags, links, and blocks

### PR DESCRIPTION
**Pull request by andersjohansson**
Here’s a pull request with three commits that could be split and pulled separately.

The main point is that I wanted more control over which trees were excluded (I often archive in-file, with the tag, and don’t want those trees to be counted). So I added a custom variable for the excluded tags.

I also needed some more control over how links were counted. Some links are references (https://gitlab.com/egh/zotxt) and could be counted as one word. Some links are in-line annotations (https://github.com/girzel/org-annotate) and there the description (which is the "marked" text) should be counted. Some links should perhaps be ignored.

Apart from this, I did some slight modernizing.

I haven’t really tested if this added complexity in `org-word-count-aux` greatly affects speed. I could put up a test document and do it more thoroughly, but I put up the code as a suggestion for now.

Another thing I haven’t tested enough is whether the change of the basic word-skip regex (from "\\w+\\W*" to "\\w+\\s-*",  "\\s-" means whitespace) is a problem. This was needed to avoid skipping into links (inside the [[]]).

### CODE REVIEW

**Comment by tesujimath** [comment]
I did a speed test on the reasonably large org file that I care to count quickly (file size of 150K or so), and it made almost no difference to the time taken (1.6 vs 1.7 seconds when timed by hand, but that's within measurement error), so I think I don't care about any possible slowdown.

If you could test the basic work-skip regex a bit more and let me know that you're happy it didn't break anything, I'll happily merge this.  (I don't really have a plan for automated testing, sorry.)

Thanks for the contribution.

**Comment by andersjohansson** [comment]
Great!

I’ll have a look at it, test the behaviour with some large files I 
have, and report back. It will probably be in a few days though.

**Comment by andersjohansson** [comment]
It’s not completely reliable with the changed regex. For example, it jumps right past block beginning lines (at least `#+BEGIN_QUOTE` but not with a space `#+BEGIN_SRC emacs-lisp`) and thus misses detecting blocks correctly. There also seemed to be some case of it skipping into links (which I thought I had avoided) so this needs to be investigated a bit more. Will look back more into it when I have time, but don’t expect this to be ready for merge just yet.

(BTW, I think counting quote blocks is reasonable, so I’m also thinking about abstracting the block detection a bit more to enable this.)

**Comment by andersjohansson** [comment]
"When I have time" ... Well, I turned the logic around, kept the old word-skipping regex and instead did a save-excursion + go back two chars for checking whether we're inside a link.

Apart from that I fixed a bug in the similar check for latex macros (wrong direction of `<`!) and added a custom variable for blocks which should actually be counted.

It all seems to work fine and as expected for me now.

**Comment by andersjohansson** [comment]
I suppose it would perhaps cleaner to smash these commits together, since they contain some back and forth changes now.

**Comment by tesujimath** [comment]
If you squash those commits together, then let me know when you're happy for it to be merged.  Cleaner is better.

**Comment by andersjohansson** [comment]
There you go! 

I did a very quick test on my current 9000 word text using a simple clock timer:

````emacs-lisp
(defmacro measure-time (&rest body)
  "Measure the time it takes to evaluate BODY."
  `(let ((time (current-time)))
     ,@body
     (message "%.06f" (float-time (time-since time)))))

(measure-time
 (dotimes (i 20)
   (org-word-count (point-min) (point-max))))
````
The new function was actually faster on this file, but I suppose that was because it excluded more:
Old: 8584 words in buffer. [20 times], 8.37 s.
New: 7115 words in buffer. [20 times], 4.65 s.

For a slightly larger file with fewer excluded trees, I get this:
Old: 16684 words in buffer. [20 times], 8.75 s
New: 16866 words in buffer. [20 times], 9.61 s 
(most probably more words since QUOTE blocks are included in the new count)

Also tried with `(org-wc-display nil)`:
Old: 16684 words in buffer. [5 times], 9.78 s
New: 16866 words in buffer. [5 times], 10.56 s

Too me these results seem reasonable.If you want to test it too feel free to do so.

**Comment by tesujimath** [comment]
Thanks.  I'll check this out as soon as I'm able and merge it if it all seems OK to me now.  (May not be immediately, sorry, have a few other things going on.)

**Comment by tesujimath** [comment]
I just tested this.  Speed is fine.  However, it now counts inside properties drawers, which the previous version didn't.  Can you fix this?

**Comment by andersjohansson** [comment]
That’s strange! Can’t immediately figure a good reason why it 
should start doing that now. I’ll have a look some time in the 
next few days.

**Comment by andersjohansson** [comment]
I have tested now and couldn’t construct any straightforward situation where it counted inside properties drawers (stepping through by edebugging `org-word-count-aux` everything seemed to work as expected). Are you sure?

A simple example which I tried, where `org-word-count` returns `8` (and stepping through shows it skipping the properties drawer).

```
A few words

* A headline
:PROPERTIES:
:CATEGORY: test
:END:

Total words should be 8
```

**Comment by tesujimath** [comment]
Sorry for the delay, I've been quite busy, hope to get back to this again before too long ...

**Comment by tesujimath** [comment]
@andersjohansson Just got round to looking at this again.  All seems fine.  Merging.

**Pull request merged**
